# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
julia:
  - 0.6
#  - nightly

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly
notifications:
  email: false

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
   - julia --check-bounds=yes --depwarn=no -e 'Pkg.clone(pwd()); Pkg.build("ConstrainedLasso"); Pkg.test("ConstrainedLasso"; coverage=true)'
#  - julia -e 'Pkg.clone(pwd()); Pkg.test("ConstrainedLasso", coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia --depwarn=no -e 'cd(Pkg.dir("ConstrainedLasso")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
  # push docs
  - julia --depwarn=no -e 'Pkg.add("Plots"); Pkg.add("ECOS"); Pkg.add("PyPlot")'
  - travis_wait 200 julia --depwarn=no -e 'Pkg.add("Documenter"); cd(Pkg.dir("ConstrainedLasso")); include(joinpath("docs", "make.jl"))'
  #- travis_wait 500 julia -e 'cd(Pkg.dir("ConstrainedLasso")); include(joinpath("docs", "make.jl"))'
#  - travis_wait 30 julia --depwarn=no -e 'Pkg.add("Plots"); ENV["PYTHON"]=""; Pkg.add("PyPlot"); Pkg.add("ECOS"); Pkg.add("Documenter"); cd(Pkg.dir("ConstrainedLasso")); include(joinpath("docs", "make.jl"))'
