# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
  - linux 
julia:
  - 0.6
  - nightly

matrix:
  allow_failures:
  - julia: nightly
notifications:
  email: false

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
script:
   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
   - julia --check-bounds=yes --depwarn=no -e 'Pkg.clone(pwd()); Pkg.build("ConstrainedLasso"); Pkg.test("ConstrainedLasso"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia --depwarn=no -e 'cd(Pkg.dir("ConstrainedLasso")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
  # push docs
  - julia -e 'Pkg.add("Documenter"); cd(Pkg.dir("ConstrainedLasso")); include(joinpath("docs", "make.jl"))'
