site_name:        ConstrainedLasso.jl
repo_url:         https://github.com/Hua-Zhou/ConstrainedLasso.jl
site_description: Constrained Lasso
site_author:      Hua Zhou and Juhyun Kim

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math
  - admonition

# extra_javascript:
#   - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
#   - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#   - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Interface: interface.md
- Example:
     - 'Fixed Tuning Parameter Value': demo/fixedparam.md
     - 'ADMM': demo/admm.md
     - 'Path Algorithm': demo/path.md
- 'Real Data Applications':
     - 'Prostate Data': demo/prostate.md
     - 'Global Warming Data': demo/warming.md
     - 'Brain Tumor Data': demo/tumor.md
     - 'Microbiome Data': demo/micro.md
- References: references.md
