site_name:        ConstrainedLasso.jl
repo_url:         https://github.com/Hua-Zhou/ConstrainedLasso.jl
site_description: Constrained Lasso
site_author:      Hua Zhou and Juhyun Kim

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math
  - admonition

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Interface: interface.md
- Example:
     - 'Fixed tuning param value': demo/fixedparam.md
     - 'Path algorithm': demo/sim.md
- 'Real Data Applications':
     - 'Prostate data': demo/prostate.md
- References: references.md
